### ISSUE TITLE
Colored file type icon

### ISSUE THREAD

**Issue by Macxim** [arcticicestudio/northem-atom-ui#1]
Maybe a dumb question but how do you get the colored file type icon?
Is there something that I have to enable?
Nice work.

**Comment by Macxim** [comment]
Alright, dumb question indeed.
See https://atom.io/packages/file-icons

**Comment by arcticicestudio** [comment]
> "The stupidest question is the question that has not been asked" 

Anyway, it's a third-party package as mentioned above. I thought about adding them intro the theme itself, but this way everyone can customize it the way they want.

Glad you like it :smile:
